modLoader = "javafml" #mandatory
loaderVersion = "[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "GNU Lesser General Public License v3.0" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "mtr" #mandatory
version = "${version}-forge" #mandatory
displayName = "Moog's Temples Reimagined" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
displayURL="https://www.curseforge.com/minecraft/mc-mods/moogs-temples-reimagined" #optional (displayed in the mod UI)
logoFile = "icon.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
credits = "Thanks to phantax, the main builder as well as TelepathicGrunt for their structure mod template and rs" #optional
authors = "FinnDog" #optional
description = '''Moogs Temples Reimagined brings life, fun and variety to your Minecraft world!
Explore awesome new structures made with vanilla blocks and entities, and discover loot,
enemies, and villagers along the way. This mod is compatible with any modpack and keeps
the vanilla feel of the game!
'''
#mandatory (Supports multiline text)
[[dependencies.mtr]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[46,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.mtr]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.5)"
ordering = "NONE"
side = "BOTH"
[[dependencies.mtr]]
modId = "moogs_structures"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

