org.gradle.jvmargs=-Xmx2G
modName=MoogsTemplesReimagined
minecraftVersion=1.21
modVersion=1.1.2
modId=mtr
modDescription=Many structures made with vanilla blocks and entities bringing life to your world! Discover loot, enemies, & villagers along the way!
modHomepage=https://www.curseforge.com/minecraft/mc-mods/mtr-moogs-temples-reimagined
modSources=https://github.com/FinnSetchell/MoogsTemplesReimagined
modReleases=https://github.com/FinnSetchell/MoogsTemplesReimagined/releases
modIssues=https://github.com/FinnSetchell/MoogsTemplesReimagined/issues
modDiscord=https://discord.gg/S5nffJbuvA
modKofi=https://ko-fi.com/finndog
modCurseforge=https://www.curseforge.com/minecraft/mc-mods/mtr-moogs-temples-reimagined
modModrinth=https://modrinth.com/mod/mtr-moogs-temples-reimagined

structureLibVersionRange=[1.0.0,)

publishDisplayPrefix=MTR
publishDisplaySuffix=[UNIVERSAL]

modrinthProjectId=UNanzCXS
curseforgeProjectId=1339737
curseforgeProjectSlug=mtr-moogs-temples-reimagined
publishMcStart=1.21
publishMcEnd=1.21.11
publishExtraMcVersions=26.1,26.1.1,26.1.2

discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/1441/430/64/64/638934556208698896.webp
discordEmbedColor=#008080
discordThumbnailUrl=https://media.forgecdn.net/avatars/thumbnails/1441/430/64/64/638934556208698896.webp
discordBannerUrl=https://www.bisecthosting.com/images/CF/Moogs_Temples_Reimagined/MP_MoogsTemplesReimagined_header.webp
discordRoleId=1466012771379581039
discordPing=true
