org.gradle.jvmargs=-Xmx2G
modName=MoogsTemplesReimagined
minecraftVersion=1.21
modVersion=1.1.0
modId=mtr

# Mod metadata
modDescription=Many structures made with vanilla blocks and entities bringing life to your world! Discover loot, enemies, & villagers along the way!
modHomepage=https://www.curseforge.com/minecraft/mc-mods/moogs-temples-reimagined
modSources=https://github.com/FinnSetchell/MoogsTemplesReimagined
modIssues=https://github.com/FinnSetchell/MoogsTemplesReimagined/issues
structureLibVersionRange=[1.1.0,)

# Publishing display customization
publishDisplayPrefix=MTR
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=UNanzCXS
curseforgeProjectId=1339737
curseforgeProjectSlug=mtr-moogs-temples-reimagined
publishMcStart=1.21
publishMcEnd=1.21.11

# Discord webhook settings
discordEmbedColor=#008080