org.gradle.jvmargs=-Xmx2G
modName=MoogsTemplesReimagined
minecraftVersion=1.20
modVersion=1.0.2
modId=mtr

# Publishing display customization
publishDisplayPrefix=MTR
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=UNanzCXS
curseforgeProjectId=1339737
publishMcStart=1.20
publishMcEnd=1.20.6
